# Pseudocode

# Lists should have.....
  # id (autogenerated integer)
  # name (string, name of the list)
  # created_at
  # updated_at

# Tasks should have.....
  # id (autogenerated integer)
  # description (text)
  # completed (boolean)
  # list_id (fk to pk of lists)
  # created_at
  # updated_at


  # A task belongs to only 1 list
  # A list has many tasks
  # This should imply a one-to-many relationship
  # the task migration should have belongs to list in there...

  # More Pseudocode
  # 1. Create the migrations, which will create the tables and columns in the DB
  # 2. Run the migrations, verify the db schema looks good
  # 3. Create 2 models, one for List, one for Task
  # 4. These models should require config/application.rb so they have AR & connection to the DB
  # 5. Create fake records and use them to seed the DB. Use Faker gem in seeds.rb & then rake


